/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package globalsystemoptionkernelcpu code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package globalsystemoptionkernelcpu

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
)

/* tools/generate-terraform-resource-full/templates/resources/common/metadata.gotmpl #metadata (cpu) */
// Metadata method to define the resource type name.
func (r systemOptionKernelCpu) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_system_option_kernel_cpu"
}
