/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package globalsystemoptionkernelcpu code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package globalsystemoptionkernelcpu

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
)

/* tools/generate-terraform-resource-full/templates/resources/common/validate.gotmpl #validate (cpu) */
// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                = &systemOptionKernelCpu{}
	_ resource.ResourceWithConfigure   = &systemOptionKernelCpu{}
	_ resource.ResourceWithImportState = &systemOptionKernelCpu{}
)

// var _ resource.ResourceWithConfigValidators = &systemOptionKernelCpu{}
// var _ resource.ResourceWithModifyPlan = &systemOptionKernelCpu{}
// var _ resource.ResourceWithUpgradeState = &systemOptionKernelCpu{}
// var _ resource.ResourceWithValidateConfig = &systemOptionKernelCpu{}

// Ensure we fully satisfy helper pkg interfaces
var _ helpers.VyosResource = &systemOptionKernelCpu{}
