/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package globalprotocolsospfredistributenhrp code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package globalprotocolsospfredistributenhrp

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
)

/* tools/generate-terraform-resource-full/templates/resources/common/metadata.gotmpl #metadata (nhrp) */
// Metadata method to define the resource type name.
func (r protocolsOspfRedistributeNhrp) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_protocols_ospf_redistribute_nhrp"
}
