/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package globalloadbalancinghaproxytimeout code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package globalloadbalancinghaproxytimeout

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/client"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/provider/data"

	// Extra Imports
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/resource/autogen/global/load-balancing/haproxy-timeout/resourcemodel"
)

/* tools/generate-terraform-resource-full/templates/resources/global/resource-node-based-full.gotmpl #resource-node-based-full (timeout) */
// NewLoadBalancingHaproxyTimeout method to return the example resource reference
func NewLoadBalancingHaproxyTimeout() resource.Resource {
	return &loadBalancingHaproxyTimeout{
		model: &resourcemodel.LoadBalancingHaproxyTimeout{},
	}
}

// loadBalancingHaproxyTimeout defines the resource implementation.
type loadBalancingHaproxyTimeout struct {
	providerData data.ProviderData
	model        *resourcemodel.LoadBalancingHaproxyTimeout
}

// GetClient returns the vyos api client
func (r *loadBalancingHaproxyTimeout) GetClient() client.Client {
	return r.providerData.Client
}

// GetModel returns the resource model
func (r *loadBalancingHaproxyTimeout) GetModel() helpers.VyosTopResourceDataModel {
	return r.model
}

// GetProviderConfig returns global provider data config
func (r *loadBalancingHaproxyTimeout) GetProviderConfig() data.ProviderData {
	return r.providerData
}

func (r *loadBalancingHaproxyTimeout) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	data, ok := req.ProviderData.(data.ProviderData)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.providerData = data
}

func (r *loadBalancingHaproxyTimeout) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
