/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package globalloadbalancinghaproxytimeout code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package globalloadbalancinghaproxytimeout

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
)

/* tools/generate-terraform-resource-full/templates/resources/common/validate.gotmpl #validate (timeout) */
// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                = &loadBalancingHaproxyTimeout{}
	_ resource.ResourceWithConfigure   = &loadBalancingHaproxyTimeout{}
	_ resource.ResourceWithImportState = &loadBalancingHaproxyTimeout{}
)

// var _ resource.ResourceWithConfigValidators = &loadBalancingHaproxyTimeout{}
// var _ resource.ResourceWithModifyPlan = &loadBalancingHaproxyTimeout{}
// var _ resource.ResourceWithUpgradeState = &loadBalancingHaproxyTimeout{}
// var _ resource.ResourceWithValidateConfig = &loadBalancingHaproxyTimeout{}

// Ensure we fully satisfy helper pkg interfaces
var _ helpers.VyosResource = &loadBalancingHaproxyTimeout{}
