
/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package resourcemodel code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"fmt"
	"net/http"
	"reflect"
	"encoding/json"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/numberplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/client"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers/crud"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/provider/data"

	
)

	/* tools/generate-terraform-resource-full/templates/resources/common/resource-model.gotmpl #resource-model (ttl) */
	// Validate compliance
	

	
	var _ helpers.VyosResourceDataModel = &FirewallBrIDgeInputFilterRuleTTL{}
	

	

	// FirewallBrIDgeInputFilterRuleTTL describes the resource data model.
	// This is not a basenode!
	// Top level basenode type: `N/A`
	type FirewallBrIDgeInputFilterRuleTTL struct {
		
			
				// LeafNodes
				LeafFirewallBrIDgeInputFilterRuleTTLEq 	types.Number `tfsdk:"eq" vyos:"eq,omitempty"`
				LeafFirewallBrIDgeInputFilterRuleTTLGt 	types.Number `tfsdk:"gt" vyos:"gt,omitempty"`
				LeafFirewallBrIDgeInputFilterRuleTTLLt 	types.Number `tfsdk:"lt" vyos:"lt,omitempty"`
				

				// TagNodes
				
				// Nodes
				
			
		
	}

	

	// ResourceSchemaAttributes generates the schema attributes for the resource at this level
	func (o FirewallBrIDgeInputFilterRuleTTL) ResourceSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
		return map[string]schema.Attribute{
			
				
					// LeafNodes
					
						"eq": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (eq) */
	schema.NumberAttribute{
			Optional:            true,
			MarkdownDescription: `Match on equal value

    |  Format  |  Description     |
    |----------|------------------|
    |  0-255   |  Equal to value  |
`,
			Description: `Match on equal value

    |  Format  |  Description     |
    |----------|------------------|
    |  0-255   |  Equal to value  |
`,
			
		},

					
						"gt": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (gt) */
	schema.NumberAttribute{
			Optional:            true,
			MarkdownDescription: `Match on greater then value

    |  Format  |  Description         |
    |----------|----------------------|
    |  0-255   |  Greater then value  |
`,
			Description: `Match on greater then value

    |  Format  |  Description         |
    |----------|----------------------|
    |  0-255   |  Greater then value  |
`,
			
		},

					
						"lt": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (lt) */
	schema.NumberAttribute{
			Optional:            true,
			MarkdownDescription: `Match on less then value

    |  Format  |  Description      |
    |----------|-------------------|
    |  0-255   |  Less then value  |
`,
			Description: `Match on less then value

    |  Format  |  Description      |
    |----------|-------------------|
    |  0-255   |  Less then value  |
`,
			
		},

					

					// TagNodes
					

					// Nodes
					
				
			
		}
	}
