
/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package resourcemodel code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"fmt"
	"net/http"
	"reflect"
	"encoding/json"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/numberplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/client"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers/crud"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/provider/data"

	
)

	/* tools/generate-terraform-resource-full/templates/resources/common/resource-model.gotmpl #resource-model (ipv6-next-hop) */
	// Validate compliance
	

	
	var _ helpers.VyosResourceDataModel = &PolicyRouteMapRuleSetIPvsixNextHop{}
	

	

	// PolicyRouteMapRuleSetIPvsixNextHop describes the resource data model.
	// This is not a basenode!
	// Top level basenode type: `N/A`
	type PolicyRouteMapRuleSetIPvsixNextHop struct {
		
			
				// LeafNodes
				LeafPolicyRouteMapRuleSetIPvsixNextHopGlobal 	types.String `tfsdk:"global" vyos:"global,omitempty"`
				LeafPolicyRouteMapRuleSetIPvsixNextHopLocal 	types.String `tfsdk:"local" vyos:"local,omitempty"`
				LeafPolicyRouteMapRuleSetIPvsixNextHopPeerAddress 	types.Bool `tfsdk:"peer_address" vyos:"peer-address,omitempty"`
				LeafPolicyRouteMapRuleSetIPvsixNextHopPreferGlobal 	types.Bool `tfsdk:"prefer_global" vyos:"prefer-global,omitempty"`
				

				// TagNodes
				
				// Nodes
				
			
		
	}

	

	// ResourceSchemaAttributes generates the schema attributes for the resource at this level
	func (o PolicyRouteMapRuleSetIPvsixNextHop) ResourceSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
		return map[string]schema.Attribute{
			
				
					// LeafNodes
					
						"global": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (global) */
	schema.StringAttribute{
			Optional:            true,
			MarkdownDescription: `Nexthop IPv6 global address

    |  Format  |  Description                     |
    |----------|----------------------------------|
    |  ipv6    |  IPv6 address and prefix length  |
`,
			Description: `Nexthop IPv6 global address

    |  Format  |  Description                     |
    |----------|----------------------------------|
    |  ipv6    |  IPv6 address and prefix length  |
`,
			
		},

					
						"local": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (local) */
	schema.StringAttribute{
			Optional:            true,
			MarkdownDescription: `Nexthop IPv6 local address

    |  Format  |  Description                     |
    |----------|----------------------------------|
    |  ipv6    |  IPv6 address and prefix length  |
`,
			Description: `Nexthop IPv6 local address

    |  Format  |  Description                     |
    |----------|----------------------------------|
    |  ipv6    |  IPv6 address and prefix length  |
`,
			
		},

					
						"peer_address": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (peer-address) */
	schema.BoolAttribute{
			Optional:            true,
			MarkdownDescription: `Use peer address (for BGP only)

`,
			Description: `Use peer address (for BGP only)

`,
			Default: booldefault.StaticBool(false),
			Computed:            true,
		},

					
						"prefer_global": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (prefer-global) */
	schema.BoolAttribute{
			Optional:            true,
			MarkdownDescription: `Prefer global address as the nexthop

`,
			Description: `Prefer global address as the nexthop

`,
			Default: booldefault.StaticBool(false),
			Computed:            true,
		},

					

					// TagNodes
					

					// Nodes
					
				
			
		}
	}
