
/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package globalprotocolsripredistributeospf code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package globalprotocolsripredistributeospf

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"fmt"
	"net/http"
	"reflect"
	"encoding/json"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/numberplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/client"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers/crud"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/provider/data"

	
)

/* tools/generate-terraform-resource-full/templates/resources/common/crud.gotmpl #crud (ospf) */
	// Create method to define the logic which creates the resource and sets its initial Terraform state.
	func (r *protocolsRIPRedistributeOspf) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
		crud.Create(ctx, r, req, resp)
	}

	// Read method to define the logic which refreshes the Terraform state for the resource.
	func (r *protocolsRIPRedistributeOspf) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
		crud.Read(ctx, r, req, resp)
	}

	// Update method to define the logic which updates the resource and sets the updated Terraform state on success.
	func (r *protocolsRIPRedistributeOspf) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
		crud.Update(ctx, r, req, resp)
	}

	// Delete method to define the logic which deletes the resource and removes the Terraform state on success.
	func (r *protocolsRIPRedistributeOspf) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
		crud.Delete(ctx, r, req, resp)
	}
