/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package namedfirewallgroupremotegroup code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package namedfirewallgroupremotegroup

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
)

/* tools/generate-terraform-resource-full/templates/resources/common/validate.gotmpl #validate (remote-group) */
// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                = &firewallGroupRemoteGroup{}
	_ resource.ResourceWithConfigure   = &firewallGroupRemoteGroup{}
	_ resource.ResourceWithImportState = &firewallGroupRemoteGroup{}
)

// var _ resource.ResourceWithConfigValidators = &firewallGroupRemoteGroup{}
// var _ resource.ResourceWithModifyPlan = &firewallGroupRemoteGroup{}
// var _ resource.ResourceWithUpgradeState = &firewallGroupRemoteGroup{}
// var _ resource.ResourceWithValidateConfig = &firewallGroupRemoteGroup{}

// Ensure we fully satisfy helper pkg interfaces
var _ helpers.VyosResource = &firewallGroupRemoteGroup{}
