
/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package resourcemodel code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"fmt"
	"net/http"
	"reflect"
	"encoding/json"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/numberplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/client"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers/crud"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/provider/data"

	
)

	/* tools/generate-terraform-resource-full/templates/resources/common/resource-model.gotmpl #resource-model (add-address-to-group) */
	// Validate compliance
	

	
	var _ helpers.VyosResourceDataModel = &FirewallIPvsixOutputFilterRuleAddAddressToGroup{}
	

	

	// FirewallIPvsixOutputFilterRuleAddAddressToGroup describes the resource data model.
	// This is not a basenode!
	// Top level basenode type: `N/A`
	type FirewallIPvsixOutputFilterRuleAddAddressToGroup struct {
		
			
				// LeafNodes
				

				// TagNodes
				
				// Nodes
				
						NodeFirewallIPvsixOutputFilterRuleAddAddressToGroupSourceAddress *FirewallIPvsixOutputFilterRuleAddAddressToGroupSourceAddress `tfsdk:"source_address" vyos:"source-address,omitempty"`
					
				
						NodeFirewallIPvsixOutputFilterRuleAddAddressToGroupDestinationAddress *FirewallIPvsixOutputFilterRuleAddAddressToGroupDestinationAddress `tfsdk:"destination_address" vyos:"destination-address,omitempty"`
					
				
			
		
	}

	

	// ResourceSchemaAttributes generates the schema attributes for the resource at this level
	func (o FirewallIPvsixOutputFilterRuleAddAddressToGroup) ResourceSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
		return map[string]schema.Attribute{
			
				
					// LeafNodes
					

					// TagNodes
					

					// Nodes
					
							"source_address": schema.SingleNestedAttribute{
								Attributes: FirewallIPvsixOutputFilterRuleAddAddressToGroupSourceAddress{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Add source ipv6 addresses to dynamic ipv6-address-group

`,
								Description: `Add source ipv6 addresses to dynamic ipv6-address-group

`,
							},
						
					
							"destination_address": schema.SingleNestedAttribute{
								Attributes: FirewallIPvsixOutputFilterRuleAddAddressToGroupDestinationAddress{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Add destination ipv6 addresses to dynamic ipv6-address-group

`,
								Description: `Add destination ipv6 addresses to dynamic ipv6-address-group

`,
							},
						
					
				
			
		}
	}
