/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package namedservicedhcpserverdynamicdnsupdatetsigkey code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package namedservicedhcpserverdynamicdnsupdatetsigkey

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/client"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/provider/data"

	// Extra Imports
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/resource/autogen/named/service/dhcp-server-dynamic-dns-update-tsig-key/resourcemodel"
)

/* tools/generate-terraform-resource-full/templates/resources/named/resource-tagnode-based-full.gotmpl #resource-tagnode-based-full (tsig-key) */
// NewServiceDhcpServerDynamicDNSUpdateTsigKey method to return the example resource reference
func NewServiceDhcpServerDynamicDNSUpdateTsigKey() resource.Resource {
	return &serviceDhcpServerDynamicDNSUpdateTsigKey{
		model: &resourcemodel.ServiceDhcpServerDynamicDNSUpdateTsigKey{},
	}
}

// serviceDhcpServerDynamicDNSUpdateTsigKey defines the resource implementation.
type serviceDhcpServerDynamicDNSUpdateTsigKey struct {
	providerData data.ProviderData
	model        *resourcemodel.ServiceDhcpServerDynamicDNSUpdateTsigKey
}

// GetClient returns the vyos api client
func (r *serviceDhcpServerDynamicDNSUpdateTsigKey) GetClient() client.Client {
	return r.providerData.Client
}

// GetModel returns the resource model
func (r *serviceDhcpServerDynamicDNSUpdateTsigKey) GetModel() helpers.VyosTopResourceDataModel {
	return r.model
}

// GetProviderConfig returns global provider data config
func (r *serviceDhcpServerDynamicDNSUpdateTsigKey) GetProviderConfig() data.ProviderData {
	return r.providerData
}

func (r *serviceDhcpServerDynamicDNSUpdateTsigKey) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	data, ok := req.ProviderData.(data.ProviderData)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.providerData = data
}

func (r *serviceDhcpServerDynamicDNSUpdateTsigKey) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
