/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package namedservicedhcpserverdynamicdnsupdatetsigkey code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package namedservicedhcpserverdynamicdnsupdatetsigkey

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
)

/* tools/generate-terraform-resource-full/templates/resources/common/validate.gotmpl #validate (tsig-key) */
// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                = &serviceDhcpServerDynamicDNSUpdateTsigKey{}
	_ resource.ResourceWithConfigure   = &serviceDhcpServerDynamicDNSUpdateTsigKey{}
	_ resource.ResourceWithImportState = &serviceDhcpServerDynamicDNSUpdateTsigKey{}
)

// var _ resource.ResourceWithConfigValidators = &serviceDhcpServerDynamicDNSUpdateTsigKey{}
// var _ resource.ResourceWithModifyPlan = &serviceDhcpServerDynamicDNSUpdateTsigKey{}
// var _ resource.ResourceWithUpgradeState = &serviceDhcpServerDynamicDNSUpdateTsigKey{}
// var _ resource.ResourceWithValidateConfig = &serviceDhcpServerDynamicDNSUpdateTsigKey{}

// Ensure we fully satisfy helper pkg interfaces
var _ helpers.VyosResource = &serviceDhcpServerDynamicDNSUpdateTsigKey{}
