
/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package resourcemodel code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"fmt"
	"net/http"
	"reflect"
	"encoding/json"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/numberplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/client"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers/crud"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/provider/data"

	
)

	/* tools/generate-terraform-resource-full/templates/resources/common/resource-model.gotmpl #resource-model (lease-time) */
	// Validate compliance
	

	
	var _ helpers.VyosResourceDataModel = &ServiceDhcpvsixServerSharedNetworkNameSubnetLeaseTime{}
	

	

	// ServiceDhcpvsixServerSharedNetworkNameSubnetLeaseTime describes the resource data model.
	// This is not a basenode!
	// Top level basenode type: `N/A`
	type ServiceDhcpvsixServerSharedNetworkNameSubnetLeaseTime struct {
		
			
				// LeafNodes
				LeafServiceDhcpvsixServerSharedNetworkNameSubnetLeaseTimeDefault 	types.Number `tfsdk:"default" vyos:"default,omitempty"`
				LeafServiceDhcpvsixServerSharedNetworkNameSubnetLeaseTimeMaximum 	types.Number `tfsdk:"maximum" vyos:"maximum,omitempty"`
				LeafServiceDhcpvsixServerSharedNetworkNameSubnetLeaseTimeMinimum 	types.Number `tfsdk:"minimum" vyos:"minimum,omitempty"`
				

				// TagNodes
				
				// Nodes
				
			
		
	}

	

	// ResourceSchemaAttributes generates the schema attributes for the resource at this level
	func (o ServiceDhcpvsixServerSharedNetworkNameSubnetLeaseTime) ResourceSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
		return map[string]schema.Attribute{
			
				
					// LeafNodes
					
						"default": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (default) */
	schema.NumberAttribute{
			Optional:            true,
			MarkdownDescription: `Default time (in seconds) that will be assigned to a lease

    |  Format        |  Description            |
    |----------------|-------------------------|
    |  1-4294967295  |  DHCPv6 valid lifetime  |
`,
			Description: `Default time (in seconds) that will be assigned to a lease

    |  Format        |  Description            |
    |----------------|-------------------------|
    |  1-4294967295  |  DHCPv6 valid lifetime  |
`,
			
		},

					
						"maximum": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (maximum) */
	schema.NumberAttribute{
			Optional:            true,
			MarkdownDescription: `Maximum time (in seconds) that will be assigned to a lease

    |  Format        |  Description                    |
    |----------------|---------------------------------|
    |  1-4294967295  |  Maximum lease time in seconds  |
`,
			Description: `Maximum time (in seconds) that will be assigned to a lease

    |  Format        |  Description                    |
    |----------------|---------------------------------|
    |  1-4294967295  |  Maximum lease time in seconds  |
`,
			
		},

					
						"minimum": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (minimum) */
	schema.NumberAttribute{
			Optional:            true,
			MarkdownDescription: `Minimum time (in seconds) that will be assigned to a lease

    |  Format        |  Description                    |
    |----------------|---------------------------------|
    |  1-4294967295  |  Minimum lease time in seconds  |
`,
			Description: `Minimum time (in seconds) that will be assigned to a lease

    |  Format        |  Description                    |
    |----------------|---------------------------------|
    |  1-4294967295  |  Minimum lease time in seconds  |
`,
			
		},

					

					// TagNodes
					

					// Nodes
					
				
			
		}
	}
