/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package globalfirewallglobaloptionsapplytobridgedtrafficacceptinvalid code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package globalfirewallglobaloptionsapplytobridgedtrafficacceptinvalid

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
)

/* tools/generate-terraform-resource-full/templates/resources/common/metadata.gotmpl #metadata (accept-invalid) */
// Metadata method to define the resource type name.
func (r firewallGlobalOptionsApplyToBrIDgedTrafficAcceptInvalID) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_firewall_global_options_apply_to_bridged_traffic_accept_invalid"
}
