/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package globalfirewallglobaloptionsapplytobridgedtrafficacceptinvalid code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package globalfirewallglobaloptionsapplytobridgedtrafficacceptinvalid

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
)

/* tools/generate-terraform-resource-full/templates/resources/common/validate.gotmpl #validate (accept-invalid) */
// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                = &firewallGlobalOptionsApplyToBrIDgedTrafficAcceptInvalID{}
	_ resource.ResourceWithConfigure   = &firewallGlobalOptionsApplyToBrIDgedTrafficAcceptInvalID{}
	_ resource.ResourceWithImportState = &firewallGlobalOptionsApplyToBrIDgedTrafficAcceptInvalID{}
)

// var _ resource.ResourceWithConfigValidators = &firewallGlobalOptionsApplyToBrIDgedTrafficAcceptInvalID{}
// var _ resource.ResourceWithModifyPlan = &firewallGlobalOptionsApplyToBrIDgedTrafficAcceptInvalID{}
// var _ resource.ResourceWithUpgradeState = &firewallGlobalOptionsApplyToBrIDgedTrafficAcceptInvalID{}
// var _ resource.ResourceWithValidateConfig = &firewallGlobalOptionsApplyToBrIDgedTrafficAcceptInvalID{}

// Ensure we fully satisfy helper pkg interfaces
var _ helpers.VyosResource = &firewallGlobalOptionsApplyToBrIDgedTrafficAcceptInvalID{}
