
/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package resourcemodel code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"fmt"
	"net/http"
	"reflect"
	"encoding/json"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/numberplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/client"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers/crud"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/provider/data"

	
)

	/* tools/generate-terraform-resource-full/templates/resources/common/resource-model.gotmpl #resource-model (client-ipv6-pool) */
	// Validate compliance
	

	
	var _ helpers.VyosResourceDataModel = &InterfacesOpenvpnServerClientIPvsixPool{}
	

	

	// InterfacesOpenvpnServerClientIPvsixPool describes the resource data model.
	// This is not a basenode!
	// Top level basenode type: `N/A`
	type InterfacesOpenvpnServerClientIPvsixPool struct {
		
			
				// LeafNodes
				LeafInterfacesOpenvpnServerClientIPvsixPoolBase 	types.String `tfsdk:"base" vyos:"base,omitempty"`
				LeafInterfacesOpenvpnServerClientIPvsixPoolDisable 	types.Bool `tfsdk:"disable" vyos:"disable,omitempty"`
				

				// TagNodes
				
				// Nodes
				
			
		
	}

	

	// ResourceSchemaAttributes generates the schema attributes for the resource at this level
	func (o InterfacesOpenvpnServerClientIPvsixPool) ResourceSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
		return map[string]schema.Attribute{
			
				
					// LeafNodes
					
						"base": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (base) */
	schema.StringAttribute{
			Optional:            true,
			MarkdownDescription: `Client IPv6 pool base address with optional prefix length

    |  Format   |  Description                                                                                                                                |
    |-----------|---------------------------------------------------------------------------------------------------------------------------------------------|
    |  ipv6net  |  Client IPv6 pool base address with optional prefix length (defaults: base = server subnet + 0x1000, prefix length = server prefix length)  |
`,
			Description: `Client IPv6 pool base address with optional prefix length

    |  Format   |  Description                                                                                                                                |
    |-----------|---------------------------------------------------------------------------------------------------------------------------------------------|
    |  ipv6net  |  Client IPv6 pool base address with optional prefix length (defaults: base = server subnet + 0x1000, prefix length = server prefix length)  |
`,
			
		},

					
						"disable": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (disable) */
	schema.BoolAttribute{
			Optional:            true,
			MarkdownDescription: `Disable instance

`,
			Description: `Disable instance

`,
			Default: booldefault.StaticBool(false),
			Computed:            true,
		},

					

					// TagNodes
					

					// Nodes
					
				
			
		}
	}
