
/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package resourcemodel code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"fmt"
	"net/http"
	"reflect"
	"encoding/json"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/numberplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/client"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers/crud"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/provider/data"

	
)

	/* tools/generate-terraform-resource-full/templates/resources/common/resource-model.gotmpl #resource-model (limit) */
	// Validate compliance
	

	
	var _ helpers.VyosResourceDataModel = &LoadBalancingWanRuleLimit{}
	

	

	// LoadBalancingWanRuleLimit describes the resource data model.
	// This is not a basenode!
	// Top level basenode type: `N/A`
	type LoadBalancingWanRuleLimit struct {
		
			
				// LeafNodes
				LeafLoadBalancingWanRuleLimitBurst 	types.Number `tfsdk:"burst" vyos:"burst,omitempty"`
				LeafLoadBalancingWanRuleLimitPeriod 	types.String `tfsdk:"period" vyos:"period,omitempty"`
				LeafLoadBalancingWanRuleLimitRate 	types.Number `tfsdk:"rate" vyos:"rate,omitempty"`
				LeafLoadBalancingWanRuleLimitThreshold 	types.String `tfsdk:"threshold" vyos:"threshold,omitempty"`
				

				// TagNodes
				
				// Nodes
				
			
		
	}

	

	// ResourceSchemaAttributes generates the schema attributes for the resource at this level
	func (o LoadBalancingWanRuleLimit) ResourceSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
		return map[string]schema.Attribute{
			
				
					// LeafNodes
					
						"burst": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (burst) */
	schema.NumberAttribute{
			Optional:            true,
			MarkdownDescription: `Burst limit for matching packets

    |  Format        |  Description                       |
    |----------------|------------------------------------|
    |  0-4294967295  |  Burst limit for matching packets  |
`,
			Description: `Burst limit for matching packets

    |  Format        |  Description                       |
    |----------------|------------------------------------|
    |  0-4294967295  |  Burst limit for matching packets  |
`,
			
				// Default:          stringdefault.StaticString(`5`),
				Computed:            true,
			
		},

					
						"period": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (period) */
	schema.StringAttribute{
			Optional:            true,
			MarkdownDescription: `Time window for rate calculation

    |  Format  |  Description  |
    |----------|---------------|
    |  hour    |  hour         |
    |  minute  |  minute       |
    |  second  |  second       |
`,
			Description: `Time window for rate calculation

    |  Format  |  Description  |
    |----------|---------------|
    |  hour    |  hour         |
    |  minute  |  minute       |
    |  second  |  second       |
`,
			
				// Default:          stringdefault.StaticString(`second`),
				Computed:            true,
			
		},

					
						"rate": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (rate) */
	schema.NumberAttribute{
			Optional:            true,
			MarkdownDescription: `Number of packets used for rate limit

    |  Format        |  Description                            |
    |----------------|-----------------------------------------|
    |  0-4294967295  |  Number of packets used for rate limit  |
`,
			Description: `Number of packets used for rate limit

    |  Format        |  Description                            |
    |----------------|-----------------------------------------|
    |  0-4294967295  |  Number of packets used for rate limit  |
`,
			
				// Default:          stringdefault.StaticString(`5`),
				Computed:            true,
			
		},

					
						"threshold": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (threshold) */
	schema.StringAttribute{
			Optional:            true,
			MarkdownDescription: `Threshold behavior for limit

    |  Format  |  Description  |
    |----------|---------------|
    |  above   |  Above limit  |
    |  below   |  Below limit  |
`,
			Description: `Threshold behavior for limit

    |  Format  |  Description  |
    |----------|---------------|
    |  above   |  Above limit  |
    |  below   |  Below limit  |
`,
			
				// Default:          stringdefault.StaticString(`below`),
				Computed:            true,
			
		},

					

					// TagNodes
					

					// Nodes
					
				
			
		}
	}
