
/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package resourcemodel code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"fmt"
	"net/http"
	"reflect"
	"encoding/json"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/numberplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/client"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers/crud"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/provider/data"

	
)

	/* tools/generate-terraform-resource-full/templates/resources/common/resource-model.gotmpl #resource-model (url-path) */
	// Validate compliance
	

	
	var _ helpers.VyosResourceDataModel = &LoadBalancingHaproxyBackendRuleURLPath{}
	

	

	// LoadBalancingHaproxyBackendRuleURLPath describes the resource data model.
	// This is not a basenode!
	// Top level basenode type: `N/A`
	type LoadBalancingHaproxyBackendRuleURLPath struct {
		
			
				// LeafNodes
				LeafLoadBalancingHaproxyBackendRuleURLPathBegin 	types.List `tfsdk:"begin" vyos:"begin,omitempty"`
				LeafLoadBalancingHaproxyBackendRuleURLPathEnd 	types.List `tfsdk:"end" vyos:"end,omitempty"`
				LeafLoadBalancingHaproxyBackendRuleURLPathExact 	types.List `tfsdk:"exact" vyos:"exact,omitempty"`
				

				// TagNodes
				
				// Nodes
				
			
		
	}

	

	// ResourceSchemaAttributes generates the schema attributes for the resource at this level
	func (o LoadBalancingHaproxyBackendRuleURLPath) ResourceSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
		return map[string]schema.Attribute{
			
				
					// LeafNodes
					
						"begin": 	
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype-multi (begin) */
	schema.ListAttribute{
			ElementType: types.StringType,
			Optional:            true,
			MarkdownDescription: `Begin URL match

    |  Format  |  Description  |
    |----------|---------------|
    |  url     |  Begin URL    |
`,
			Description: `Begin URL match

    |  Format  |  Description  |
    |----------|---------------|
    |  url     |  Begin URL    |
`,
			
		},

											
					
						"end": 	
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype-multi (end) */
	schema.ListAttribute{
			ElementType: types.StringType,
			Optional:            true,
			MarkdownDescription: `End URL match

    |  Format  |  Description  |
    |----------|---------------|
    |  url     |  End URL      |
`,
			Description: `End URL match

    |  Format  |  Description  |
    |----------|---------------|
    |  url     |  End URL      |
`,
			
		},

											
					
						"exact": 	
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype-multi (exact) */
	schema.ListAttribute{
			ElementType: types.StringType,
			Optional:            true,
			MarkdownDescription: `Exactly URL match

    |  Format  |  Description  |
    |----------|---------------|
    |  url     |  Exactly URL  |
`,
			Description: `Exactly URL match

    |  Format  |  Description  |
    |----------|---------------|
    |  url     |  Exactly URL  |
`,
			
		},

											
					

					// TagNodes
					

					// Nodes
					
				
			
		}
	}
