/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package resourcemodel code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
)

/* tools/generate-terraform-resource-full/templates/resources/common/resource-model.gotmpl #resource-model (traffic-selector) */
// Validate compliance

var _ helpers.VyosResourceDataModel = &VpnIPsecSiteToSitePeerVtiTrafficSelector{}

// VpnIPsecSiteToSitePeerVtiTrafficSelector describes the resource data model.
// This is not a basenode!
// Top level basenode type: `N/A`
type VpnIPsecSiteToSitePeerVtiTrafficSelector struct {
	// LeafNodes

	// TagNodes

	// Nodes

	NodeVpnIPsecSiteToSitePeerVtiTrafficSelectorLocal *VpnIPsecSiteToSitePeerVtiTrafficSelectorLocal `tfsdk:"local" vyos:"local,omitempty"`

	NodeVpnIPsecSiteToSitePeerVtiTrafficSelectorRemote *VpnIPsecSiteToSitePeerVtiTrafficSelectorRemote `tfsdk:"remote" vyos:"remote,omitempty"`
}

// ResourceSchemaAttributes generates the schema attributes for the resource at this level
func (o VpnIPsecSiteToSitePeerVtiTrafficSelector) ResourceSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
	return map[string]schema.Attribute{
		// LeafNodes

		// TagNodes

		// Nodes

		"local": schema.SingleNestedAttribute{
			Attributes: VpnIPsecSiteToSitePeerVtiTrafficSelectorLocal{}.ResourceSchemaAttributes(ctx),
			Optional:   true,
			MarkdownDescription: `Local parameters for interesting traffic

`,
			Description: `Local parameters for interesting traffic

`,
		},

		"remote": schema.SingleNestedAttribute{
			Attributes: VpnIPsecSiteToSitePeerVtiTrafficSelectorRemote{}.ResourceSchemaAttributes(ctx),
			Optional:   true,
			MarkdownDescription: `Remote parameters for interesting traffic

`,
			Description: `Remote parameters for interesting traffic

`,
		},
	}
}
