
/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package resourcemodel code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"fmt"
	"net/http"
	"reflect"
	"encoding/json"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/numberplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/client"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers/crud"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/provider/data"

	
)

	/* tools/generate-terraform-resource-full/templates/resources/common/resource-model.gotmpl #resource-model (privacy) */
	// Validate compliance
	

	
	var _ helpers.VyosResourceDataModel = &ServiceSnmpVthreeTrapTargetPrivacy{}
	

	

	// ServiceSnmpVthreeTrapTargetPrivacy describes the resource data model.
	// This is not a basenode!
	// Top level basenode type: `N/A`
	type ServiceSnmpVthreeTrapTargetPrivacy struct {
		
			
				// LeafNodes
				LeafServiceSnmpVthreeTrapTargetPrivacyEncryptedPassword 	types.String `tfsdk:"encrypted_password" vyos:"encrypted-password,omitempty"`
				LeafServiceSnmpVthreeTrapTargetPrivacyPlaintextPassword 	types.String `tfsdk:"plaintext_password" vyos:"plaintext-password,omitempty"`
				LeafServiceSnmpVthreeTrapTargetPrivacyType 	types.String `tfsdk:"type" vyos:"type,omitempty"`
				

				// TagNodes
				
				// Nodes
				
			
		
	}

	

	// ResourceSchemaAttributes generates the schema attributes for the resource at this level
	func (o ServiceSnmpVthreeTrapTargetPrivacy) ResourceSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
		return map[string]schema.Attribute{
			
				
					// LeafNodes
					
						"encrypted_password": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (encrypted-password) */
	schema.StringAttribute{
			Optional:            true,
			MarkdownDescription: `Defines the encrypted key for privacy protocol

`,
			Description: `Defines the encrypted key for privacy protocol

`,
			
		},

					
						"plaintext_password": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (plaintext-password) */
	schema.StringAttribute{
			Optional:            true,
			MarkdownDescription: `Defines the clear text key for privacy protocol

`,
			Description: `Defines the clear text key for privacy protocol

`,
			
		},

					
						"type": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (type) */
	schema.StringAttribute{
			Optional:            true,
			MarkdownDescription: `Defines the protocol for privacy

    |  Format  |  Description                   |
    |----------|--------------------------------|
    |  des     |  Data Encryption Standard      |
    |  aes     |  Advanced Encryption Standard  |
`,
			Description: `Defines the protocol for privacy

    |  Format  |  Description                   |
    |----------|--------------------------------|
    |  des     |  Data Encryption Standard      |
    |  aes     |  Advanced Encryption Standard  |
`,
			
				// Default:          stringdefault.StaticString(`des`),
				Computed:            true,
			
		},

					

					// TagNodes
					

					// Nodes
					
				
			
		}
	}
