/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package namedservicedhcpserverdynamicdnsupdatereversedomain code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package namedservicedhcpserverdynamicdnsupdatereversedomain

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
)

/* tools/generate-terraform-resource-full/templates/resources/common/validate.gotmpl #validate (reverse-domain) */
// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                = &serviceDhcpServerDynamicDNSUpdateReverseDomain{}
	_ resource.ResourceWithConfigure   = &serviceDhcpServerDynamicDNSUpdateReverseDomain{}
	_ resource.ResourceWithImportState = &serviceDhcpServerDynamicDNSUpdateReverseDomain{}
)

// var _ resource.ResourceWithConfigValidators = &serviceDhcpServerDynamicDNSUpdateReverseDomain{}
// var _ resource.ResourceWithModifyPlan = &serviceDhcpServerDynamicDNSUpdateReverseDomain{}
// var _ resource.ResourceWithUpgradeState = &serviceDhcpServerDynamicDNSUpdateReverseDomain{}
// var _ resource.ResourceWithValidateConfig = &serviceDhcpServerDynamicDNSUpdateReverseDomain{}

// Ensure we fully satisfy helper pkg interfaces
var _ helpers.VyosResource = &serviceDhcpServerDynamicDNSUpdateReverseDomain{}
