
/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package globalservicemonitoringtelegrafprometheusclient code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package globalservicemonitoringtelegrafprometheusclient

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"fmt"
	"net/http"
	"reflect"
	"encoding/json"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/numberplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/client"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers/crud"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/provider/data"

	
)

/* tools/generate-terraform-resource-full/templates/resources/common/validate.gotmpl #validate (prometheus-client) */
	// Ensure provider defined types fully satisfy framework interfaces.
	var _ resource.Resource = &serviceMonitoringTelegrafPrometheusClient{}
	var _ resource.ResourceWithConfigure = &serviceMonitoringTelegrafPrometheusClient{}
	var _ resource.ResourceWithImportState = &serviceMonitoringTelegrafPrometheusClient{}
	// var _ resource.ResourceWithConfigValidators = &serviceMonitoringTelegrafPrometheusClient{}
	// var _ resource.ResourceWithModifyPlan = &serviceMonitoringTelegrafPrometheusClient{}
	// var _ resource.ResourceWithUpgradeState = &serviceMonitoringTelegrafPrometheusClient{}
	// var _ resource.ResourceWithValidateConfig = &serviceMonitoringTelegrafPrometheusClient{}

	// Ensure we fully satisfy helper pkg interfaces
	var _ helpers.VyosResource = &serviceMonitoringTelegrafPrometheusClient{}
