/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package resourcemodel code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
)

/* tools/generate-terraform-resource-full/templates/resources/common/resource-model.gotmpl #resource-model (dynamic-dns-update) */
// Validate compliance

var _ helpers.VyosTopResourceDataModel = &ServiceDhcpServerDynamicDNSUpdate{}

// ServiceDhcpServerDynamicDNSUpdate describes the resource data model.
// This is a basenode!
// Top level basenode type: `Node`
type ServiceDhcpServerDynamicDNSUpdate struct {
	ID       types.String   `tfsdk:"id" vyos:"-,tfsdk-id"`
	Timeouts timeouts.Value `tfsdk:"timeouts" vyos:"-,timeout"`

	// LeafNodes
	LeafServiceDhcpServerDynamicDNSUpdateSendUpdates             types.String `tfsdk:"send_updates" vyos:"send-updates,omitempty"`
	LeafServiceDhcpServerDynamicDNSUpdateOverrIDeClientUpdate    types.String `tfsdk:"override_client_update" vyos:"override-client-update,omitempty"`
	LeafServiceDhcpServerDynamicDNSUpdateOverrIDeNoUpdate        types.String `tfsdk:"override_no_update" vyos:"override-no-update,omitempty"`
	LeafServiceDhcpServerDynamicDNSUpdateReplaceClientName       types.String `tfsdk:"replace_client_name" vyos:"replace-client-name,omitempty"`
	LeafServiceDhcpServerDynamicDNSUpdateGeneratedPrefix         types.String `tfsdk:"generated_prefix" vyos:"generated-prefix,omitempty"`
	LeafServiceDhcpServerDynamicDNSUpdateQualifyingSuffix        types.String `tfsdk:"qualifying_suffix" vyos:"qualifying-suffix,omitempty"`
	LeafServiceDhcpServerDynamicDNSUpdateUpdateOnRenew           types.String `tfsdk:"update_on_renew" vyos:"update-on-renew,omitempty"`
	LeafServiceDhcpServerDynamicDNSUpdateConflictResolution      types.String `tfsdk:"conflict_resolution" vyos:"conflict-resolution,omitempty"`
	LeafServiceDhcpServerDynamicDNSUpdateTTLPercent              types.String `tfsdk:"ttl_percent" vyos:"ttl-percent,omitempty"`
	LeafServiceDhcpServerDynamicDNSUpdateHostnameCharSet         types.String `tfsdk:"hostname_char_set" vyos:"hostname-char-set,omitempty"`
	LeafServiceDhcpServerDynamicDNSUpdateHostnameCharReplacement types.String `tfsdk:"hostname_char_replacement" vyos:"hostname-char-replacement,omitempty"`

	// TagNodes

	ExistsTagServiceDhcpServerDynamicDNSUpdateTsigKey bool `tfsdk:"-" vyos:"tsig-key,child"`

	ExistsTagServiceDhcpServerDynamicDNSUpdateForwardDomain bool `tfsdk:"-" vyos:"forward-domain,child"`

	ExistsTagServiceDhcpServerDynamicDNSUpdateReverseDomain bool `tfsdk:"-" vyos:"reverse-domain,child"`

	// Nodes
}

// SetID configures the resource ID
func (o *ServiceDhcpServerDynamicDNSUpdate) SetID(id []string) {
	o.ID = basetypes.NewStringValue(strings.Join(id, "__"))
}

// GetTimeouts returns resource timeout config
func (o *ServiceDhcpServerDynamicDNSUpdate) GetTimeouts() timeouts.Value {
	return o.Timeouts
}

// IsGlobalResource returns true if this is global
// This is useful during CRUD delete
func (o *ServiceDhcpServerDynamicDNSUpdate) IsGlobalResource() bool {
	return (true)
}

// GetVyosPath returns the list of strings to use to get to the correct vyos configuration
func (o *ServiceDhcpServerDynamicDNSUpdate) GetVyosPath() []string {
	return append(
		o.GetVyosParentPath(),
		"dynamic-dns-update",
	)
}

// GetVyosParentPath returns the list of strings to use to get to the correct
// vyos configuration for the nearest parent.
// If this is the top level resource the list might end up returning the entire interface definition tree.
// This is intended to use with the resource CRUD read function to check for empty resources.
func (o *ServiceDhcpServerDynamicDNSUpdate) GetVyosParentPath() []string {
	return []string{
		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-parent-vyos-path-hack.gotmpl #resource-model-parent-vyos-path-hack (dhcp-server) */

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-parent-vyos-path-hack.gotmpl #resource-model-parent-vyos-path-hack (service) */
		"service", // Node

		"dhcp-server", // Node

	}
}

// GetVyosNamedParentPath returns the list of strings to use to get to the correct
// vyos configuration for the nearest parent that is not a global resource.
// If this is the top level named resource the list is zero elements long.
// This is intended to use with the resource CRUD create function to check if the required parent exists.
func (o *ServiceDhcpServerDynamicDNSUpdate) GetVyosNamedParentPath() []string {
	return []string{
		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-parent-vyos-path-hack.gotmpl #resource-model-parent-vyos-path-hack-for-non-global (dhcp-server) */

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-parent-vyos-path-hack.gotmpl #resource-model-parent-vyos-path-hack-for-non-global (service) */

	}
}

// ResourceSchemaAttributes generates the schema attributes for the resource at this level
func (o ServiceDhcpServerDynamicDNSUpdate) ResourceSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Computed:            true,
			MarkdownDescription: "Resource ID, full vyos path to the resource with each field separated by dunder (`__`).",
		},

		"timeouts": timeouts.Attributes(ctx, timeouts.Opts{
			Create: true,
		}),

		// LeafNodes

		"send_updates":

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (send-updates) */
		schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `Enable or disable updates for this scope

    |  Format   |  Description                     |
    |-----------|----------------------------------|
    |  enable   |  Enable updates for this scope   |
    |  disable  |  Disable updates for this scope  |
`,
			Description: `Enable or disable updates for this scope

    |  Format   |  Description                     |
    |-----------|----------------------------------|
    |  enable   |  Enable updates for this scope   |
    |  disable  |  Disable updates for this scope  |
`,
		},

		"override_client_update":

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (override-client-update) */
		schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `Always update both forward and reverse DNS data, regardless of the client's request

    |  Format   |  Description                                        |
    |-----------|-----------------------------------------------------|
    |  enable   |  Force update both forward and reverse DNS records  |
    |  disable  |  Respect client request settings                    |
`,
			Description: `Always update both forward and reverse DNS data, regardless of the client's request

    |  Format   |  Description                                        |
    |-----------|-----------------------------------------------------|
    |  enable   |  Force update both forward and reverse DNS records  |
    |  disable  |  Respect client request settings                    |
`,
		},

		"override_no_update":

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (override-no-update) */
		schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `Perform a DDNS update, even if the client instructs the server not to

    |  Format   |  Description                                      |
    |-----------|---------------------------------------------------|
    |  enable   |  Force DDNS updates regardless of client request  |
    |  disable  |  Respect client request settings                  |
`,
			Description: `Perform a DDNS update, even if the client instructs the server not to

    |  Format   |  Description                                      |
    |-----------|---------------------------------------------------|
    |  enable   |  Force DDNS updates regardless of client request  |
    |  disable  |  Respect client request settings                  |
`,
		},

		"replace_client_name":

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (replace-client-name) */
		schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `Replace client name mode

    |  Format            |  Description                                                                                                |
    |--------------------|-------------------------------------------------------------------------------------------------------------|
    |  never             |  Use the name the client sent. If the client sent no name, do not generate
                one              |
    |  always            |  Replace the name the client sent. If the client sent no name, generate one
                for the client  |
    |  when-present      |  Replace the name the client sent. If the client sent no name, do not
                generate one          |
    |  when-not-present  |  Use the name the client sent. If the client sent no name, generate one for
                the client      |
`,
			Description: `Replace client name mode

    |  Format            |  Description                                                                                                |
    |--------------------|-------------------------------------------------------------------------------------------------------------|
    |  never             |  Use the name the client sent. If the client sent no name, do not generate
                one              |
    |  always            |  Replace the name the client sent. If the client sent no name, generate one
                for the client  |
    |  when-present      |  Replace the name the client sent. If the client sent no name, do not
                generate one          |
    |  when-not-present  |  Use the name the client sent. If the client sent no name, generate one for
                the client      |
`,
		},

		"generated_prefix":

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (generated-prefix) */
		schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `The prefix used in the generation of an FQDN

`,
			Description: `The prefix used in the generation of an FQDN

`,
		},

		"qualifying_suffix":

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (qualifying-suffix) */
		schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `The suffix used when generating an FQDN, or when qualifying a partial name

`,
			Description: `The suffix used when generating an FQDN, or when qualifying a partial name

`,
		},

		"update_on_renew":

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (update-on-renew) */
		schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `Update DNS record on lease renew

    |  Format   |  Description                              |
    |-----------|-------------------------------------------|
    |  enable   |  Update DNS record on lease renew         |
    |  disable  |  Do not update DNS record on lease renew  |
`,
			Description: `Update DNS record on lease renew

    |  Format   |  Description                              |
    |-----------|-------------------------------------------|
    |  enable   |  Update DNS record on lease renew         |
    |  disable  |  Do not update DNS record on lease renew  |
`,
		},

		"conflict_resolution":

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (conflict-resolution) */
		schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `DNS conflict resolution behavior

    |  Format   |  Description                      |
    |-----------|-----------------------------------|
    |  enable   |  Enable DNS conflict resolution   |
    |  disable  |  Disable DNS conflict resolution  |
`,
			Description: `DNS conflict resolution behavior

    |  Format   |  Description                      |
    |-----------|-----------------------------------|
    |  enable   |  Enable DNS conflict resolution   |
    |  disable  |  Disable DNS conflict resolution  |
`,
		},

		"ttl_percent":

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (ttl-percent) */
		schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `Calculate TTL of the DNS record as a percentage of the lease lifetime

`,
			Description: `Calculate TTL of the DNS record as a percentage of the lease lifetime

`,
		},

		"hostname_char_set":

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (hostname-char-set) */
		schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `A regular expression describing the invalid character set in the host name

`,
			Description: `A regular expression describing the invalid character set in the host name

`,
		},

		"hostname_char_replacement":

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (hostname-char-replacement) */
		schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `A string of zero or more characters with which to replace each invalid character in
            the host name

`,
			Description: `A string of zero or more characters with which to replace each invalid character in
            the host name

`,
		},

		// TagNodes

		// Nodes

	}
}
