/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package resourcemodel code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
)

/* tools/generate-terraform-resource-full/templates/resources/common/resource-model.gotmpl #resource-model (cpu) */
// Validate compliance

var _ helpers.VyosTopResourceDataModel = &SystemOptionKernelCpu{}

// SystemOptionKernelCpu describes the resource data model.
// This is a basenode!
// Top level basenode type: `Node`
type SystemOptionKernelCpu struct {
	ID       types.String   `tfsdk:"id" vyos:"-,tfsdk-id"`
	Timeouts timeouts.Value `tfsdk:"timeouts" vyos:"-,timeout"`

	// LeafNodes
	LeafSystemOptionKernelCpuDisableNmiWatchdog types.Bool   `tfsdk:"disable_nmi_watchdog" vyos:"disable-nmi-watchdog,omitempty"`
	LeafSystemOptionKernelCpuIsolateCpus        types.String `tfsdk:"isolate_cpus" vyos:"isolate-cpus,omitempty"`
	LeafSystemOptionKernelCpuNohzFull           types.String `tfsdk:"nohz_full" vyos:"nohz-full,omitempty"`
	LeafSystemOptionKernelCpuRcuNoCbs           types.String `tfsdk:"rcu_no_cbs" vyos:"rcu-no-cbs,omitempty"`

	// TagNodes

	// Nodes
}

// SetID configures the resource ID
func (o *SystemOptionKernelCpu) SetID(id []string) {
	o.ID = basetypes.NewStringValue(strings.Join(id, "__"))
}

// GetTimeouts returns resource timeout config
func (o *SystemOptionKernelCpu) GetTimeouts() timeouts.Value {
	return o.Timeouts
}

// IsGlobalResource returns true if this is global
// This is useful during CRUD delete
func (o *SystemOptionKernelCpu) IsGlobalResource() bool {
	return (true)
}

// GetVyosPath returns the list of strings to use to get to the correct vyos configuration
func (o *SystemOptionKernelCpu) GetVyosPath() []string {
	return append(
		o.GetVyosParentPath(),
		"cpu",
	)
}

// GetVyosParentPath returns the list of strings to use to get to the correct
// vyos configuration for the nearest parent.
// If this is the top level resource the list might end up returning the entire interface definition tree.
// This is intended to use with the resource CRUD read function to check for empty resources.
func (o *SystemOptionKernelCpu) GetVyosParentPath() []string {
	return []string{
		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-parent-vyos-path-hack.gotmpl #resource-model-parent-vyos-path-hack (kernel) */

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-parent-vyos-path-hack.gotmpl #resource-model-parent-vyos-path-hack (option) */

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-parent-vyos-path-hack.gotmpl #resource-model-parent-vyos-path-hack (system) */
		"system", // Node

		"option", // Node

		"kernel", // Node

	}
}

// GetVyosNamedParentPath returns the list of strings to use to get to the correct
// vyos configuration for the nearest parent that is not a global resource.
// If this is the top level named resource the list is zero elements long.
// This is intended to use with the resource CRUD create function to check if the required parent exists.
func (o *SystemOptionKernelCpu) GetVyosNamedParentPath() []string {
	return []string{
		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-parent-vyos-path-hack.gotmpl #resource-model-parent-vyos-path-hack-for-non-global (kernel) */

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-parent-vyos-path-hack.gotmpl #resource-model-parent-vyos-path-hack-for-non-global (option) */

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-parent-vyos-path-hack.gotmpl #resource-model-parent-vyos-path-hack-for-non-global (system) */

	}
}

// ResourceSchemaAttributes generates the schema attributes for the resource at this level
func (o SystemOptionKernelCpu) ResourceSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Computed:            true,
			MarkdownDescription: "Resource ID, full vyos path to the resource with each field separated by dunder (`__`).",
		},

		"timeouts": timeouts.Attributes(ctx, timeouts.Opts{
			Create: true,
		}),

		// LeafNodes

		"disable_nmi_watchdog":

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (disable-nmi-watchdog) */
		schema.BoolAttribute{
			Optional: true,
			MarkdownDescription: `Disable the NMI watchdog for detecting hard CPU lockups

`,
			Description: `Disable the NMI watchdog for detecting hard CPU lockups

`,
			Default:  booldefault.StaticBool(false),
			Computed: true,
		},

		"isolate_cpus":

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (isolate-cpus) */
		schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `Isolate specified CPUs from the scheduler

    |  Format       |  Description                                       |
    |---------------|----------------------------------------------------|
    |  0-511        |  CPU core                                          |
    |  <start-end>  |  CPU core range (examples: "1", "4-7", "1,2-5,7")  |
`,
			Description: `Isolate specified CPUs from the scheduler

    |  Format       |  Description                                       |
    |---------------|----------------------------------------------------|
    |  0-511        |  CPU core                                          |
    |  <start-end>  |  CPU core range (examples: "1", "4-7", "1,2-5,7")  |
`,
		},

		"nohz_full":

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (nohz-full) */
		schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `Enable full tickless mode for specified CPUs

    |  Format       |  Description                                       |
    |---------------|----------------------------------------------------|
    |  0-511        |  CPU core                                          |
    |  <start-end>  |  CPU core range (examples: "1", "4-7", "1,2-5,7")  |
`,
			Description: `Enable full tickless mode for specified CPUs

    |  Format       |  Description                                       |
    |---------------|----------------------------------------------------|
    |  0-511        |  CPU core                                          |
    |  <start-end>  |  CPU core range (examples: "1", "4-7", "1,2-5,7")  |
`,
		},

		"rcu_no_cbs":

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (rcu-no-cbs) */
		schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `Offload Read-Copy-Update (RCU) callback processing to specified CPUs

    |  Format       |  Description                                       |
    |---------------|----------------------------------------------------|
    |  0-511        |  CPU core                                          |
    |  <start-end>  |  CPU core range (examples: "1", "4-7", "1,2-5,7")  |
`,
			Description: `Offload Read-Copy-Update (RCU) callback processing to specified CPUs

    |  Format       |  Description                                       |
    |---------------|----------------------------------------------------|
    |  0-511        |  CPU core                                          |
    |  <start-end>  |  CPU core range (examples: "1", "4-7", "1,2-5,7")  |
`,
		},

		// TagNodes

		// Nodes

	}
}
