/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package namedservicedhcpserverdynamicdnsupdateforwarddomaindnsserver code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package namedservicedhcpserverdynamicdnsupdateforwarddomaindnsserver

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
)

/* tools/generate-terraform-resource-full/templates/resources/common/validate.gotmpl #validate (dns-server) */
// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                = &serviceDhcpServerDynamicDNSUpdateForwardDomainDNSServer{}
	_ resource.ResourceWithConfigure   = &serviceDhcpServerDynamicDNSUpdateForwardDomainDNSServer{}
	_ resource.ResourceWithImportState = &serviceDhcpServerDynamicDNSUpdateForwardDomainDNSServer{}
)

// var _ resource.ResourceWithConfigValidators = &serviceDhcpServerDynamicDNSUpdateForwardDomainDNSServer{}
// var _ resource.ResourceWithModifyPlan = &serviceDhcpServerDynamicDNSUpdateForwardDomainDNSServer{}
// var _ resource.ResourceWithUpgradeState = &serviceDhcpServerDynamicDNSUpdateForwardDomainDNSServer{}
// var _ resource.ResourceWithValidateConfig = &serviceDhcpServerDynamicDNSUpdateForwardDomainDNSServer{}

// Ensure we fully satisfy helper pkg interfaces
var _ helpers.VyosResource = &serviceDhcpServerDynamicDNSUpdateForwardDomainDNSServer{}
