
/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package resourcemodel code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"fmt"
	"net/http"
	"reflect"
	"encoding/json"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/numberplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/client"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers/crud"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/provider/data"

	
)

	/* tools/generate-terraform-resource-full/templates/resources/common/resource-model.gotmpl #resource-model (ipv4-unicast) */
	// Validate compliance
	

	
	var _ helpers.VyosResourceDataModel = &ProtocolsBgpAddressFamilyIPvfourUnicast{}
	

	

	// ProtocolsBgpAddressFamilyIPvfourUnicast describes the resource data model.
	// This is not a basenode!
	// Top level basenode type: `N/A`
	type ProtocolsBgpAddressFamilyIPvfourUnicast struct {
		
			
				// LeafNodes
				

				// TagNodes
				
						ExistsTagProtocolsBgpAddressFamilyIPvfourUnicastAggregateAddress bool `tfsdk:"-" vyos:"aggregate-address,child"`
					
				
						ExistsTagProtocolsBgpAddressFamilyIPvfourUnicastNetwork bool `tfsdk:"-" vyos:"network,child"`
					
				
				// Nodes
				
						ExistsNodeProtocolsBgpAddressFamilyIPvfourUnicastDistance bool `tfsdk:"-" vyos:"distance,child"`
					
				
						ExistsNodeProtocolsBgpAddressFamilyIPvfourUnicastExport bool `tfsdk:"-" vyos:"export,child"`
					
				
						ExistsNodeProtocolsBgpAddressFamilyIPvfourUnicastImport bool `tfsdk:"-" vyos:"import,child"`
					
				
						// Ignoring Node `ProtocolsBgpAddressFamilyIPvfourUnicastLabel`.
					
				
						ExistsNodeProtocolsBgpAddressFamilyIPvfourUnicastMaximumPaths bool `tfsdk:"-" vyos:"maximum-paths,child"`
					
				
						// Ignoring Node `ProtocolsBgpAddressFamilyIPvfourUnicastRd`.
					
				
						// Ignoring Node `ProtocolsBgpAddressFamilyIPvfourUnicastRouteMap`.
					
				
						// Ignoring Node `ProtocolsBgpAddressFamilyIPvfourUnicastRouteTarget`.
					
				
						// Ignoring Node `ProtocolsBgpAddressFamilyIPvfourUnicastNexthop`.
					
				
						// Ignoring Node `ProtocolsBgpAddressFamilyIPvfourUnicastRedistribute`.
					
				
						// Ignoring Node `ProtocolsBgpAddressFamilyIPvfourUnicastSID`.
					
				
			
		
	}

	

	// ResourceSchemaAttributes generates the schema attributes for the resource at this level
	func (o ProtocolsBgpAddressFamilyIPvfourUnicast) ResourceSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
		return map[string]schema.Attribute{
			
				
					// LeafNodes
					

					// TagNodes
					
					
					

					// Nodes
					
					
					
					
					
					
					
					
					
					
					
					
				
			
		}
	}
