/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package resourcemodel code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
)

/* tools/generate-terraform-resource-full/templates/resources/common/resource-model.gotmpl #resource-model (timeout) */
// Validate compliance

var _ helpers.VyosResourceDataModel = &LoadBalancingHaproxyServiceTimeout{}

// LoadBalancingHaproxyServiceTimeout describes the resource data model.
// This is not a basenode!
// Top level basenode type: `N/A`
type LoadBalancingHaproxyServiceTimeout struct {
	// LeafNodes
	LeafLoadBalancingHaproxyServiceTimeoutClient types.Number `tfsdk:"client" vyos:"client,omitempty"`

	// TagNodes

	// Nodes
}

// ResourceSchemaAttributes generates the schema attributes for the resource at this level
func (o LoadBalancingHaproxyServiceTimeout) ResourceSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
	return map[string]schema.Attribute{
		// LeafNodes

		"client":

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (client) */
		schema.NumberAttribute{
			Optional: true,
			MarkdownDescription: `Maximum inactivity time on the client side

    |  Format  |  Description         |
    |----------|----------------------|
    |  1-3600  |  Timeout in seconds  |
`,
			Description: `Maximum inactivity time on the client side

    |  Format  |  Description         |
    |----------|----------------------|
    |  1-3600  |  Timeout in seconds  |
`,
		},

		// TagNodes

		// Nodes

	}
}
