/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package namedcontainernametmpfs code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package namedcontainernametmpfs

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
)

/* tools/generate-terraform-resource-full/templates/resources/common/validate.gotmpl #validate (tmpfs) */
// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                = &containerNameTmpfs{}
	_ resource.ResourceWithConfigure   = &containerNameTmpfs{}
	_ resource.ResourceWithImportState = &containerNameTmpfs{}
)

// var _ resource.ResourceWithConfigValidators = &containerNameTmpfs{}
// var _ resource.ResourceWithModifyPlan = &containerNameTmpfs{}
// var _ resource.ResourceWithUpgradeState = &containerNameTmpfs{}
// var _ resource.ResourceWithValidateConfig = &containerNameTmpfs{}

// Ensure we fully satisfy helper pkg interfaces
var _ helpers.VyosResource = &containerNameTmpfs{}
