/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package namedsystemipimporttable code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package namedsystemipimporttable

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
)

/* tools/generate-terraform-resource-full/templates/resources/common/validate.gotmpl #validate (import-table) */
// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                = &systemIPImportTable{}
	_ resource.ResourceWithConfigure   = &systemIPImportTable{}
	_ resource.ResourceWithImportState = &systemIPImportTable{}
)

// var _ resource.ResourceWithConfigValidators = &systemIPImportTable{}
// var _ resource.ResourceWithModifyPlan = &systemIPImportTable{}
// var _ resource.ResourceWithUpgradeState = &systemIPImportTable{}
// var _ resource.ResourceWithValidateConfig = &systemIPImportTable{}

// Ensure we fully satisfy helper pkg interfaces
var _ helpers.VyosResource = &systemIPImportTable{}
