/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package resourcemodel code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
)

/* tools/generate-terraform-resource-full/templates/resources/common/resource-model.gotmpl #resource-model (accept-invalid) */
// Validate compliance

var _ helpers.VyosTopResourceDataModel = &FirewallGlobalOptionsApplyToBrIDgedTrafficAcceptInvalID{}

// FirewallGlobalOptionsApplyToBrIDgedTrafficAcceptInvalID describes the resource data model.
// This is a basenode!
// Top level basenode type: `Node`
type FirewallGlobalOptionsApplyToBrIDgedTrafficAcceptInvalID struct {
	ID       types.String   `tfsdk:"id" vyos:"-,tfsdk-id"`
	Timeouts timeouts.Value `tfsdk:"timeouts" vyos:"-,timeout"`

	// LeafNodes
	LeafFirewallGlobalOptionsApplyToBrIDgedTrafficAcceptInvalIDEthernetType types.List `tfsdk:"ethernet_type" vyos:"ethernet-type,omitempty"`

	// TagNodes

	// Nodes
}

// SetID configures the resource ID
func (o *FirewallGlobalOptionsApplyToBrIDgedTrafficAcceptInvalID) SetID(id []string) {
	o.ID = basetypes.NewStringValue(strings.Join(id, "__"))
}

// GetTimeouts returns resource timeout config
func (o *FirewallGlobalOptionsApplyToBrIDgedTrafficAcceptInvalID) GetTimeouts() timeouts.Value {
	return o.Timeouts
}

// IsGlobalResource returns true if this is global
// This is useful during CRUD delete
func (o *FirewallGlobalOptionsApplyToBrIDgedTrafficAcceptInvalID) IsGlobalResource() bool {
	return (true)
}

// GetVyosPath returns the list of strings to use to get to the correct vyos configuration
func (o *FirewallGlobalOptionsApplyToBrIDgedTrafficAcceptInvalID) GetVyosPath() []string {
	return append(
		o.GetVyosParentPath(),
		"accept-invalid",
	)
}

// GetVyosParentPath returns the list of strings to use to get to the correct
// vyos configuration for the nearest parent.
// If this is the top level resource the list might end up returning the entire interface definition tree.
// This is intended to use with the resource CRUD read function to check for empty resources.
func (o *FirewallGlobalOptionsApplyToBrIDgedTrafficAcceptInvalID) GetVyosParentPath() []string {
	return []string{
		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-parent-vyos-path-hack.gotmpl #resource-model-parent-vyos-path-hack (apply-to-bridged-traffic) */

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-parent-vyos-path-hack.gotmpl #resource-model-parent-vyos-path-hack (global-options) */

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-parent-vyos-path-hack.gotmpl #resource-model-parent-vyos-path-hack (firewall) */
		"firewall", // Node

		"global-options", // Node

		"apply-to-bridged-traffic", // Node

	}
}

// GetVyosNamedParentPath returns the list of strings to use to get to the correct
// vyos configuration for the nearest parent that is not a global resource.
// If this is the top level named resource the list is zero elements long.
// This is intended to use with the resource CRUD create function to check if the required parent exists.
func (o *FirewallGlobalOptionsApplyToBrIDgedTrafficAcceptInvalID) GetVyosNamedParentPath() []string {
	return []string{
		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-parent-vyos-path-hack.gotmpl #resource-model-parent-vyos-path-hack-for-non-global (apply-to-bridged-traffic) */

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-parent-vyos-path-hack.gotmpl #resource-model-parent-vyos-path-hack-for-non-global (global-options) */

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-parent-vyos-path-hack.gotmpl #resource-model-parent-vyos-path-hack-for-non-global (firewall) */

	}
}

// ResourceSchemaAttributes generates the schema attributes for the resource at this level
func (o FirewallGlobalOptionsApplyToBrIDgedTrafficAcceptInvalID) ResourceSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Computed:            true,
			MarkdownDescription: "Resource ID, full vyos path to the resource with each field separated by dunder (`__`).",
		},

		"timeouts": timeouts.Attributes(ctx, timeouts.Opts{
			Create: true,
		}),

		// LeafNodes

		"ethernet_type":
		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype-multi (ethernet-type) */
		schema.ListAttribute{
			ElementType: types.StringType,
			Optional:    true,
			MarkdownDescription: `Ethernet type

    |  Format           |  Description                                   |
    |-------------------|------------------------------------------------|
    |  arp              |  Adress Resolution Protocol (ARP)              |
    |  dhcp             |  Dynamic Host Configuration Protocol (DHCP)    |
    |  pppoe            |  Point to Point over Ethernet (PPPoE) Session  |
    |  pppoe-discovery  |  PPPoE Discovery                               |
    |  802.1q           |  Customer VLAN tag type (802.1Q)               |
    |  802.1ad          |  Service VLAN tag type (802.1ad)               |
    |  wol              |  Wake-on-LAN magic packet                      |
`,
			Description: `Ethernet type

    |  Format           |  Description                                   |
    |-------------------|------------------------------------------------|
    |  arp              |  Adress Resolution Protocol (ARP)              |
    |  dhcp             |  Dynamic Host Configuration Protocol (DHCP)    |
    |  pppoe            |  Point to Point over Ethernet (PPPoE) Session  |
    |  pppoe-discovery  |  PPPoE Discovery                               |
    |  802.1q           |  Customer VLAN tag type (802.1Q)               |
    |  802.1ad          |  Service VLAN tag type (802.1ad)               |
    |  wol              |  Wake-on-LAN magic packet                      |
`,
		},

		// TagNodes

		// Nodes

	}
}
