/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package globalsystemoptionkernelmemory code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package globalsystemoptionkernelmemory

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
)

/* tools/generate-terraform-resource-full/templates/resources/common/validate.gotmpl #validate (memory) */
// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                = &systemOptionKernelMemory{}
	_ resource.ResourceWithConfigure   = &systemOptionKernelMemory{}
	_ resource.ResourceWithImportState = &systemOptionKernelMemory{}
)

// var _ resource.ResourceWithConfigValidators = &systemOptionKernelMemory{}
// var _ resource.ResourceWithModifyPlan = &systemOptionKernelMemory{}
// var _ resource.ResourceWithUpgradeState = &systemOptionKernelMemory{}
// var _ resource.ResourceWithValidateConfig = &systemOptionKernelMemory{}

// Ensure we fully satisfy helper pkg interfaces
var _ helpers.VyosResource = &systemOptionKernelMemory{}
