
/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package resourcemodel code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"fmt"
	"net/http"
	"reflect"
	"encoding/json"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/numberplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/client"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers/crud"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/provider/data"

	
)

	/* tools/generate-terraform-resource-full/templates/resources/common/resource-model.gotmpl #resource-model (authentication) */
	// Validate compliance
	

	
	var _ helpers.VyosResourceDataModel = &HighAvailabilityVrrpGroupAuthentication{}
	

	

	// HighAvailabilityVrrpGroupAuthentication describes the resource data model.
	// This is not a basenode!
	// Top level basenode type: `N/A`
	type HighAvailabilityVrrpGroupAuthentication struct {
		
			
				// LeafNodes
				LeafHighAvailabilityVrrpGroupAuthenticationPassword 	types.String `tfsdk:"password" vyos:"password,omitempty"`
				LeafHighAvailabilityVrrpGroupAuthenticationType 	types.String `tfsdk:"type" vyos:"type,omitempty"`
				

				// TagNodes
				
				// Nodes
				
			
		
	}

	

	// ResourceSchemaAttributes generates the schema attributes for the resource at this level
	func (o HighAvailabilityVrrpGroupAuthentication) ResourceSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
		return map[string]schema.Attribute{
			
				
					// LeafNodes
					
						"password": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (password) */
	schema.StringAttribute{
			Optional:            true,
			MarkdownDescription: `VRRP password

    |  Format  |  Description                           |
    |----------|----------------------------------------|
    |  txt     |  Password string (up to 8 characters)  |
`,
			Description: `VRRP password

    |  Format  |  Description                           |
    |----------|----------------------------------------|
    |  txt     |  Password string (up to 8 characters)  |
`,
			
		},

					
						"type": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (type) */
	schema.StringAttribute{
			Optional:            true,
			MarkdownDescription: `Authentication type

    |  Format              |  Description                   |
    |----------------------|--------------------------------|
    |  plaintext-password  |  Simple password string        |
    |  ah                  |  AH - IPSEC (not recommended)  |
`,
			Description: `Authentication type

    |  Format              |  Description                   |
    |----------------------|--------------------------------|
    |  plaintext-password  |  Simple password string        |
    |  ah                  |  AH - IPSEC (not recommended)  |
`,
			
		},

					

					// TagNodes
					

					// Nodes
					
				
			
		}
	}
