
/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package resourcemodel code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"fmt"
	"net/http"
	"reflect"
	"encoding/json"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/numberplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/client"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers/crud"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/provider/data"

	
)

	/* tools/generate-terraform-resource-full/templates/resources/common/resource-model.gotmpl #resource-model (location) */
	// Validate compliance
	

	
	var _ helpers.VyosResourceDataModel = &ServiceLldpInterfaceLocation{}
	

	

	// ServiceLldpInterfaceLocation describes the resource data model.
	// This is not a basenode!
	// Top level basenode type: `N/A`
	type ServiceLldpInterfaceLocation struct {
		
			
				// LeafNodes
				LeafServiceLldpInterfaceLocationElin 	types.Number `tfsdk:"elin" vyos:"elin,omitempty"`
				

				// TagNodes
				
				// Nodes
				
						NodeServiceLldpInterfaceLocationCoordinateBased *ServiceLldpInterfaceLocationCoordinateBased `tfsdk:"coordinate_based" vyos:"coordinate-based,omitempty"`
					
				
			
		
	}

	

	// ResourceSchemaAttributes generates the schema attributes for the resource at this level
	func (o ServiceLldpInterfaceLocation) ResourceSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
		return map[string]schema.Attribute{
			
				
					// LeafNodes
					
						"elin": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (elin) */
	schema.NumberAttribute{
			Optional:            true,
			MarkdownDescription: `ECS ELIN (Emergency location identifier number)

    |  Format        |  Description                                                 |
    |----------------|--------------------------------------------------------------|
    |  0-9999999999  |  Emergency Call Service ELIN number (between 10-25 numbers)  |
`,
			Description: `ECS ELIN (Emergency location identifier number)

    |  Format        |  Description                                                 |
    |----------------|--------------------------------------------------------------|
    |  0-9999999999  |  Emergency Call Service ELIN number (between 10-25 numbers)  |
`,
			
		},

					

					// TagNodes
					

					// Nodes
					
							"coordinate_based": schema.SingleNestedAttribute{
								Attributes: ServiceLldpInterfaceLocationCoordinateBased{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Coordinate based location

`,
								Description: `Coordinate based location

`,
							},
						
					
				
			
		}
	}
