/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package namedloadbalancinghaproxyservicelistenaddress code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package namedloadbalancinghaproxyservicelistenaddress

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
)

/* tools/generate-terraform-resource-full/templates/resources/common/validate.gotmpl #validate (listen-address) */
// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                = &loadBalancingHaproxyServiceListenAddress{}
	_ resource.ResourceWithConfigure   = &loadBalancingHaproxyServiceListenAddress{}
	_ resource.ResourceWithImportState = &loadBalancingHaproxyServiceListenAddress{}
)

// var _ resource.ResourceWithConfigValidators = &loadBalancingHaproxyServiceListenAddress{}
// var _ resource.ResourceWithModifyPlan = &loadBalancingHaproxyServiceListenAddress{}
// var _ resource.ResourceWithUpgradeState = &loadBalancingHaproxyServiceListenAddress{}
// var _ resource.ResourceWithValidateConfig = &loadBalancingHaproxyServiceListenAddress{}

// Ensure we fully satisfy helper pkg interfaces
var _ helpers.VyosResource = &loadBalancingHaproxyServiceListenAddress{}
