
/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package resourcemodel code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"fmt"
	"net/http"
	"reflect"
	"encoding/json"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/numberplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/client"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers/crud"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/provider/data"

	
)

	/* tools/generate-terraform-resource-full/templates/resources/common/resource-model.gotmpl #resource-model (ipv4) */
	// Validate compliance
	

	
	var _ helpers.VyosResourceDataModel = &VrfNameProtocolsIsisRedistributeIPvfour{}
	

	

	// VrfNameProtocolsIsisRedistributeIPvfour describes the resource data model.
	// This is not a basenode!
	// Top level basenode type: `N/A`
	type VrfNameProtocolsIsisRedistributeIPvfour struct {
		
			
				// LeafNodes
				

				// TagNodes
				
				// Nodes
				
						NodeVrfNameProtocolsIsisRedistributeIPvfourBgp *VrfNameProtocolsIsisRedistributeIPvfourBgp `tfsdk:"bgp" vyos:"bgp,omitempty"`
					
				
						NodeVrfNameProtocolsIsisRedistributeIPvfourConnected *VrfNameProtocolsIsisRedistributeIPvfourConnected `tfsdk:"connected" vyos:"connected,omitempty"`
					
				
						NodeVrfNameProtocolsIsisRedistributeIPvfourKernel *VrfNameProtocolsIsisRedistributeIPvfourKernel `tfsdk:"kernel" vyos:"kernel,omitempty"`
					
				
						NodeVrfNameProtocolsIsisRedistributeIPvfourNhrp *VrfNameProtocolsIsisRedistributeIPvfourNhrp `tfsdk:"nhrp" vyos:"nhrp,omitempty"`
					
				
						NodeVrfNameProtocolsIsisRedistributeIPvfourOspf *VrfNameProtocolsIsisRedistributeIPvfourOspf `tfsdk:"ospf" vyos:"ospf,omitempty"`
					
				
						NodeVrfNameProtocolsIsisRedistributeIPvfourRIP *VrfNameProtocolsIsisRedistributeIPvfourRIP `tfsdk:"rip" vyos:"rip,omitempty"`
					
				
						NodeVrfNameProtocolsIsisRedistributeIPvfourBabel *VrfNameProtocolsIsisRedistributeIPvfourBabel `tfsdk:"babel" vyos:"babel,omitempty"`
					
				
						NodeVrfNameProtocolsIsisRedistributeIPvfourStatic *VrfNameProtocolsIsisRedistributeIPvfourStatic `tfsdk:"static" vyos:"static,omitempty"`
					
				
			
		
	}

	

	// ResourceSchemaAttributes generates the schema attributes for the resource at this level
	func (o VrfNameProtocolsIsisRedistributeIPvfour) ResourceSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
		return map[string]schema.Attribute{
			
				
					// LeafNodes
					

					// TagNodes
					

					// Nodes
					
							"bgp": schema.SingleNestedAttribute{
								Attributes: VrfNameProtocolsIsisRedistributeIPvfourBgp{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Border Gateway Protocol (BGP)

`,
								Description: `Border Gateway Protocol (BGP)

`,
							},
						
					
							"connected": schema.SingleNestedAttribute{
								Attributes: VrfNameProtocolsIsisRedistributeIPvfourConnected{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Redistribute connected routes into IS-IS

`,
								Description: `Redistribute connected routes into IS-IS

`,
							},
						
					
							"kernel": schema.SingleNestedAttribute{
								Attributes: VrfNameProtocolsIsisRedistributeIPvfourKernel{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Redistribute kernel routes into IS-IS

`,
								Description: `Redistribute kernel routes into IS-IS

`,
							},
						
					
							"nhrp": schema.SingleNestedAttribute{
								Attributes: VrfNameProtocolsIsisRedistributeIPvfourNhrp{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Redistribute NHRP routes into IS-IS

`,
								Description: `Redistribute NHRP routes into IS-IS

`,
							},
						
					
							"ospf": schema.SingleNestedAttribute{
								Attributes: VrfNameProtocolsIsisRedistributeIPvfourOspf{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Redistribute OSPF routes into IS-IS

`,
								Description: `Redistribute OSPF routes into IS-IS

`,
							},
						
					
							"rip": schema.SingleNestedAttribute{
								Attributes: VrfNameProtocolsIsisRedistributeIPvfourRIP{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Redistribute RIP routes into IS-IS

`,
								Description: `Redistribute RIP routes into IS-IS

`,
							},
						
					
							"babel": schema.SingleNestedAttribute{
								Attributes: VrfNameProtocolsIsisRedistributeIPvfourBabel{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Redistribute Babel routes into IS-IS

`,
								Description: `Redistribute Babel routes into IS-IS

`,
							},
						
					
							"static": schema.SingleNestedAttribute{
								Attributes: VrfNameProtocolsIsisRedistributeIPvfourStatic{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Redistribute static routes into IS-IS

`,
								Description: `Redistribute static routes into IS-IS

`,
							},
						
					
				
			
		}
	}
