
/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package resourcemodel code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"fmt"
	"net/http"
	"reflect"
	"encoding/json"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/numberplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/client"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers/crud"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/provider/data"

	
)

	/* tools/generate-terraform-resource-full/templates/resources/common/resource-model.gotmpl #resource-model (ipv6) */
	// Validate compliance
	

	
	var _ helpers.VyosResourceDataModel = &VrfNameProtocolsIsisRedistributeIPvsix{}
	

	

	// VrfNameProtocolsIsisRedistributeIPvsix describes the resource data model.
	// This is not a basenode!
	// Top level basenode type: `N/A`
	type VrfNameProtocolsIsisRedistributeIPvsix struct {
		
			
				// LeafNodes
				

				// TagNodes
				
				// Nodes
				
						NodeVrfNameProtocolsIsisRedistributeIPvsixBgp *VrfNameProtocolsIsisRedistributeIPvsixBgp `tfsdk:"bgp" vyos:"bgp,omitempty"`
					
				
						NodeVrfNameProtocolsIsisRedistributeIPvsixConnected *VrfNameProtocolsIsisRedistributeIPvsixConnected `tfsdk:"connected" vyos:"connected,omitempty"`
					
				
						NodeVrfNameProtocolsIsisRedistributeIPvsixKernel *VrfNameProtocolsIsisRedistributeIPvsixKernel `tfsdk:"kernel" vyos:"kernel,omitempty"`
					
				
						NodeVrfNameProtocolsIsisRedistributeIPvsixOspfsix *VrfNameProtocolsIsisRedistributeIPvsixOspfsix `tfsdk:"ospf6" vyos:"ospf6,omitempty"`
					
				
						NodeVrfNameProtocolsIsisRedistributeIPvsixRIPng *VrfNameProtocolsIsisRedistributeIPvsixRIPng `tfsdk:"ripng" vyos:"ripng,omitempty"`
					
				
						NodeVrfNameProtocolsIsisRedistributeIPvsixBabel *VrfNameProtocolsIsisRedistributeIPvsixBabel `tfsdk:"babel" vyos:"babel,omitempty"`
					
				
						NodeVrfNameProtocolsIsisRedistributeIPvsixStatic *VrfNameProtocolsIsisRedistributeIPvsixStatic `tfsdk:"static" vyos:"static,omitempty"`
					
				
			
		
	}

	

	// ResourceSchemaAttributes generates the schema attributes for the resource at this level
	func (o VrfNameProtocolsIsisRedistributeIPvsix) ResourceSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
		return map[string]schema.Attribute{
			
				
					// LeafNodes
					

					// TagNodes
					

					// Nodes
					
							"bgp": schema.SingleNestedAttribute{
								Attributes: VrfNameProtocolsIsisRedistributeIPvsixBgp{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Redistribute BGP routes into IS-IS

`,
								Description: `Redistribute BGP routes into IS-IS

`,
							},
						
					
							"connected": schema.SingleNestedAttribute{
								Attributes: VrfNameProtocolsIsisRedistributeIPvsixConnected{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Redistribute connected routes into IS-IS

`,
								Description: `Redistribute connected routes into IS-IS

`,
							},
						
					
							"kernel": schema.SingleNestedAttribute{
								Attributes: VrfNameProtocolsIsisRedistributeIPvsixKernel{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Redistribute kernel routes into IS-IS

`,
								Description: `Redistribute kernel routes into IS-IS

`,
							},
						
					
							"ospf6": schema.SingleNestedAttribute{
								Attributes: VrfNameProtocolsIsisRedistributeIPvsixOspfsix{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Redistribute OSPFv3 routes into IS-IS

`,
								Description: `Redistribute OSPFv3 routes into IS-IS

`,
							},
						
					
							"ripng": schema.SingleNestedAttribute{
								Attributes: VrfNameProtocolsIsisRedistributeIPvsixRIPng{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Redistribute RIPng routes into IS-IS

`,
								Description: `Redistribute RIPng routes into IS-IS

`,
							},
						
					
							"babel": schema.SingleNestedAttribute{
								Attributes: VrfNameProtocolsIsisRedistributeIPvsixBabel{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Redistribute Babel routes into IS-IS

`,
								Description: `Redistribute Babel routes into IS-IS

`,
							},
						
					
							"static": schema.SingleNestedAttribute{
								Attributes: VrfNameProtocolsIsisRedistributeIPvsixStatic{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Redistribute static routes into IS-IS

`,
								Description: `Redistribute static routes into IS-IS

`,
							},
						
					
				
			
		}
	}
