
/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package resourcemodel code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"fmt"
	"net/http"
	"reflect"
	"encoding/json"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/numberplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/client"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers/crud"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/provider/data"

	
)

	/* tools/generate-terraform-resource-full/templates/resources/common/resource-model.gotmpl #resource-model (global) */
	// Validate compliance
	

	
	var _ helpers.VyosResourceDataModel = &VrfNameProtocolsBgpParametersDistanceGlobal{}
	

	

	// VrfNameProtocolsBgpParametersDistanceGlobal describes the resource data model.
	// This is not a basenode!
	// Top level basenode type: `N/A`
	type VrfNameProtocolsBgpParametersDistanceGlobal struct {
		
			
				// LeafNodes
				LeafVrfNameProtocolsBgpParametersDistanceGlobalExternal 	types.Number `tfsdk:"external" vyos:"external,omitempty"`
				LeafVrfNameProtocolsBgpParametersDistanceGlobalInternal 	types.Number `tfsdk:"internal" vyos:"internal,omitempty"`
				LeafVrfNameProtocolsBgpParametersDistanceGlobalLocal 	types.Number `tfsdk:"local" vyos:"local,omitempty"`
				

				// TagNodes
				
				// Nodes
				
			
		
	}

	

	// ResourceSchemaAttributes generates the schema attributes for the resource at this level
	func (o VrfNameProtocolsBgpParametersDistanceGlobal) ResourceSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
		return map[string]schema.Attribute{
			
				
					// LeafNodes
					
						"external": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (external) */
	schema.NumberAttribute{
			Optional:            true,
			MarkdownDescription: `Administrative distance for external BGP routes

    |  Format  |  Description                                      |
    |----------|---------------------------------------------------|
    |  1-255   |  Administrative distance for external BGP routes  |
`,
			Description: `Administrative distance for external BGP routes

    |  Format  |  Description                                      |
    |----------|---------------------------------------------------|
    |  1-255   |  Administrative distance for external BGP routes  |
`,
			
		},

					
						"internal": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (internal) */
	schema.NumberAttribute{
			Optional:            true,
			MarkdownDescription: `Administrative distance for internal BGP routes

    |  Format  |  Description                                      |
    |----------|---------------------------------------------------|
    |  1-255   |  Administrative distance for internal BGP routes  |
`,
			Description: `Administrative distance for internal BGP routes

    |  Format  |  Description                                      |
    |----------|---------------------------------------------------|
    |  1-255   |  Administrative distance for internal BGP routes  |
`,
			
		},

					
						"local": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (local) */
	schema.NumberAttribute{
			Optional:            true,
			MarkdownDescription: `Administrative distance for local BGP routes

    |  Format  |  Description                                      |
    |----------|---------------------------------------------------|
    |  1-255   |  Administrative distance for internal BGP routes  |
`,
			Description: `Administrative distance for local BGP routes

    |  Format  |  Description                                      |
    |----------|---------------------------------------------------|
    |  1-255   |  Administrative distance for internal BGP routes  |
`,
			
		},

					

					// TagNodes
					

					// Nodes
					
				
			
		}
	}
