
/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package resourcemodel code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"fmt"
	"net/http"
	"reflect"
	"encoding/json"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/numberplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/client"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers/crud"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/provider/data"

	
)

	/* tools/generate-terraform-resource-full/templates/resources/common/resource-model.gotmpl #resource-model (graceful-restart) */
	// Validate compliance
	

	
	var _ helpers.VyosResourceDataModel = &VrfNameProtocolsOspfvthreeGracefulRestart{}
	

	

	// VrfNameProtocolsOspfvthreeGracefulRestart describes the resource data model.
	// This is not a basenode!
	// Top level basenode type: `N/A`
	type VrfNameProtocolsOspfvthreeGracefulRestart struct {
		
			
				// LeafNodes
				LeafVrfNameProtocolsOspfvthreeGracefulRestartGracePeriod 	types.Number `tfsdk:"grace_period" vyos:"grace-period,omitempty"`
				

				// TagNodes
				
				// Nodes
				
						NodeVrfNameProtocolsOspfvthreeGracefulRestartHelper *VrfNameProtocolsOspfvthreeGracefulRestartHelper `tfsdk:"helper" vyos:"helper,omitempty"`
					
				
			
		
	}

	

	// ResourceSchemaAttributes generates the schema attributes for the resource at this level
	func (o VrfNameProtocolsOspfvthreeGracefulRestart) ResourceSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
		return map[string]schema.Attribute{
			
				
					// LeafNodes
					
						"grace_period": 	
												
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (grace-period) */
	schema.NumberAttribute{
			Optional:            true,
			MarkdownDescription: `Maximum length of the grace period

    |  Format  |  Description                                    |
    |----------|-------------------------------------------------|
    |  1-1800  |  Maximum length of the grace period in seconds  |
`,
			Description: `Maximum length of the grace period

    |  Format  |  Description                                    |
    |----------|-------------------------------------------------|
    |  1-1800  |  Maximum length of the grace period in seconds  |
`,
			
				// Default:          stringdefault.StaticString(`120`),
				Computed:            true,
			
		},

					

					// TagNodes
					

					// Nodes
					
							"helper": schema.SingleNestedAttribute{
								Attributes: VrfNameProtocolsOspfvthreeGracefulRestartHelper{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `OSPF graceful-restart helpers

`,
								Description: `OSPF graceful-restart helpers

`,
							},
						
					
				
			
		}
	}
