
/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package resourcemodel code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"fmt"
	"net/http"
	"reflect"
	"encoding/json"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/numberplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/client"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers/crud"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/provider/data"

	
)

	/* tools/generate-terraform-resource-full/templates/resources/common/resource-model.gotmpl #resource-model (protocols) */
	// Validate compliance
	

	
	var _ helpers.VyosResourceDataModel = &VrfNameProtocols{}
	

	

	// VrfNameProtocols describes the resource data model.
	// This is not a basenode!
	// Top level basenode type: `N/A`
	type VrfNameProtocols struct {
		
			
				// LeafNodes
				

				// TagNodes
				
				// Nodes
				
						NodeVrfNameProtocolsBgp *VrfNameProtocolsBgp `tfsdk:"bgp" vyos:"bgp,omitempty"`
					
				
						NodeVrfNameProtocolsEigrp *VrfNameProtocolsEigrp `tfsdk:"eigrp" vyos:"eigrp,omitempty"`
					
				
						NodeVrfNameProtocolsIsis *VrfNameProtocolsIsis `tfsdk:"isis" vyos:"isis,omitempty"`
					
				
						NodeVrfNameProtocolsOspf *VrfNameProtocolsOspf `tfsdk:"ospf" vyos:"ospf,omitempty"`
					
				
						NodeVrfNameProtocolsOspfvthree *VrfNameProtocolsOspfvthree `tfsdk:"ospfv3" vyos:"ospfv3,omitempty"`
					
				
						NodeVrfNameProtocolsRpki *VrfNameProtocolsRpki `tfsdk:"rpki" vyos:"rpki,omitempty"`
					
				
						// Ignoring Node `VrfNameProtocolsStatic`.
					
				
			
		
	}

	

	// ResourceSchemaAttributes generates the schema attributes for the resource at this level
	func (o VrfNameProtocols) ResourceSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
		return map[string]schema.Attribute{
			
				
					// LeafNodes
					

					// TagNodes
					

					// Nodes
					
							"bgp": schema.SingleNestedAttribute{
								Attributes: VrfNameProtocolsBgp{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Border Gateway Protocol (BGP)

`,
								Description: `Border Gateway Protocol (BGP)

`,
							},
						
					
							"eigrp": schema.SingleNestedAttribute{
								Attributes: VrfNameProtocolsEigrp{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Enhanced Interior Gateway Routing Protocol (EIGRP)

`,
								Description: `Enhanced Interior Gateway Routing Protocol (EIGRP)

`,
							},
						
					
							"isis": schema.SingleNestedAttribute{
								Attributes: VrfNameProtocolsIsis{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Intermediate System to Intermediate System (IS-IS)

`,
								Description: `Intermediate System to Intermediate System (IS-IS)

`,
							},
						
					
							"ospf": schema.SingleNestedAttribute{
								Attributes: VrfNameProtocolsOspf{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Open Shortest Path First (OSPF)

`,
								Description: `Open Shortest Path First (OSPF)

`,
							},
						
					
							"ospfv3": schema.SingleNestedAttribute{
								Attributes: VrfNameProtocolsOspfvthree{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Open Shortest Path First (OSPF) for IPv6

`,
								Description: `Open Shortest Path First (OSPF) for IPv6

`,
							},
						
					
							"rpki": schema.SingleNestedAttribute{
								Attributes: VrfNameProtocolsRpki{}.ResourceSchemaAttributes(ctx),
								Optional:            true,
								MarkdownDescription: `Resource Public Key Infrastructure (RPKI)

`,
								Description: `Resource Public Key Infrastructure (RPKI)

`,
							},
						
					
					
				
			
		}
	}
