
/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package resourcemodel code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"
	"fmt"
	"net/http"
	"reflect"
	"encoding/json"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/numberplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"

	"github.com/echowings/terraform-provider-vyos-rolling/internal/client"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/helpers/crud"
	"github.com/echowings/terraform-provider-vyos-rolling/internal/terraform/provider/data"

	
)

	/* tools/generate-terraform-resource-full/templates/resources/common/resource-model.gotmpl #resource-model (route-target) */
	// Validate compliance
	

	
	var _ helpers.VyosResourceDataModel = &VrfNameProtocolsBgpAddressFamilyLtwovpnEvpnRouteTarget{}
	

	

	// VrfNameProtocolsBgpAddressFamilyLtwovpnEvpnRouteTarget describes the resource data model.
	// This is not a basenode!
	// Top level basenode type: `N/A`
	type VrfNameProtocolsBgpAddressFamilyLtwovpnEvpnRouteTarget struct {
		
			
				// LeafNodes
				LeafVrfNameProtocolsBgpAddressFamilyLtwovpnEvpnRouteTargetBoth 	types.List `tfsdk:"both" vyos:"both,omitempty"`
				LeafVrfNameProtocolsBgpAddressFamilyLtwovpnEvpnRouteTargetImport 	types.List `tfsdk:"import" vyos:"import,omitempty"`
				LeafVrfNameProtocolsBgpAddressFamilyLtwovpnEvpnRouteTargetExport 	types.List `tfsdk:"export" vyos:"export,omitempty"`
				

				// TagNodes
				
				// Nodes
				
			
		
	}

	

	// ResourceSchemaAttributes generates the schema attributes for the resource at this level
	func (o VrfNameProtocolsBgpAddressFamilyLtwovpnEvpnRouteTarget) ResourceSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
		return map[string]schema.Attribute{
			
				
					// LeafNodes
					
						"both": 	
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype-multi (both) */
	schema.ListAttribute{
			ElementType: types.StringType,
			Optional:            true,
			MarkdownDescription: `Route Target both import and export

    |  Format  |  Description                                |
    |----------|---------------------------------------------|
    |  txt     |  Route target (A.B.C.D:MN|EF:OPQR|GHJK:MN)  |
`,
			Description: `Route Target both import and export

    |  Format  |  Description                                |
    |----------|---------------------------------------------|
    |  txt     |  Route target (A.B.C.D:MN|EF:OPQR|GHJK:MN)  |
`,
			
		},

											
					
						"import": 	
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype-multi (import) */
	schema.ListAttribute{
			ElementType: types.StringType,
			Optional:            true,
			MarkdownDescription: `Route Target import

    |  Format  |  Description                                |
    |----------|---------------------------------------------|
    |  txt     |  Route target (A.B.C.D:MN|EF:OPQR|GHJK:MN)  |
`,
			Description: `Route Target import

    |  Format  |  Description                                |
    |----------|---------------------------------------------|
    |  txt     |  Route target (A.B.C.D:MN|EF:OPQR|GHJK:MN)  |
`,
			
		},

											
					
						"export": 	
/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype-multi (export) */
	schema.ListAttribute{
			ElementType: types.StringType,
			Optional:            true,
			MarkdownDescription: `Route Target export

    |  Format  |  Description                                |
    |----------|---------------------------------------------|
    |  txt     |  Route target (A.B.C.D:MN|EF:OPQR|GHJK:MN)  |
`,
			Description: `Route Target export

    |  Format  |  Description                                |
    |----------|---------------------------------------------|
    |  txt     |  Route target (A.B.C.D:MN|EF:OPQR|GHJK:MN)  |
`,
			
		},

											
					

					// TagNodes
					

					// Nodes
					
				
			
		}
	}
